/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fox35_walk.glb --types 
*/

import * as THREE from "three";
import React, { useEffect, type JSX } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { type GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "rig|rig|walk";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    fox35_1: THREE.SkinnedMesh;
    fox35_2: THREE.SkinnedMesh;
    fox35_3: THREE.SkinnedMesh;
    body: THREE.Bone;
  };
  materials: {
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/fox35_walk.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions, names } = useAnimations(animations, group);
  // 3. Play an animation when the component mounts
  useEffect(() => {
    // Check available animation names in console if you aren't sure
    console.log(names);

    // Replace 'Idle' with the actual name of your animation
    const action = actions["rig|rig|walk"];

    if (action) {
      action.reset().fadeIn(0.5).play();
    }

    // Cleanup: Stop animation when unmounting
    return () => {
      if (action) action.fadeOut(0.5);
    };
  }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.body} />
          <group name="fox35">
            <skinnedMesh
              name="fox35_1"
              geometry={nodes.fox35_1.geometry}
              material={materials["Material.004"]}
              skeleton={nodes.fox35_1.skeleton}
            />
            <skinnedMesh
              name="fox35_2"
              geometry={nodes.fox35_2.geometry}
              material={materials["Material.005"]}
              skeleton={nodes.fox35_2.skeleton}
            />
            <skinnedMesh
              name="fox35_3"
              geometry={nodes.fox35_3.geometry}
              material={materials["Material.006"]}
              skeleton={nodes.fox35_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/fox35_walk.glb");
